(****************************************************************************)
(* Jeroo is a programming language learning tool for students and teachers. *)
(* Copyright (C) <2019>  <Benjamin Konz>                                    *)
(*                                                                          *)
(* This program is free software: you can redistribute it and/or modify     *)
(* it under the terms of the GNU Affero General Public License as           *)
(* published by the Free Software Foundation, either version 3 of the       *)
(* License, or (at your option) any later version.                          *)
(*                                                                          *)
(* This program is distributed in the hope that it will be useful,          *)
(* but WITHOUT ANY WARRANTY; without even the implied warranty of           *)
(* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            *)
(* GNU Affero General Public License for more details.                      *)
(*                                                                          *)
(* You should have received a copy of the GNU Affero General Public License *)
(* along with this program.  If not, see <http://www.gnu.org/licenses/>.    *)
(****************************************************************************)

let map_token = function
  | VBParser.TRUE (_, s)
  | VBParser.FALSE (_, s)
  | VBParser.SUB (_, s)
  | VBParser.IF (_, s)
  | VBParser.ELSE (_, s)
  | VBParser.WHILE (_, s)
  | VBParser.ENDSUB (_, s)
  | VBParser.ENDIF (_, s)
  | VBParser.ENDWHILE (_, s)
  | VBParser.ELSEIF (_, s)
  | VBParser.AND (_, s)
  | VBParser.OR (_, s)
  | VBParser.NOT (_, s)
  | VBParser.EQ (_, s)
  | VBParser.NEW (_, s)
  | VBParser.DOT (_, s)
  | VBParser.LEFT (_, s)
  | VBParser.RIGHT (_, s)
  | VBParser.AHEAD (_, s)
  | VBParser.HERE (_, s)
  | VBParser.NORTH (_, s)
  | VBParser.SOUTH (_, s)
  | VBParser.EAST (_, s)
  | VBParser.WEST (_, s)
  | VBParser.LPAREN (_, s)
  | VBParser.RPAREN (_, s)
  | VBParser.COMMA (_, s)
  | VBParser.THEN (_, s)
  | VBParser.DIM (_, s)
  | VBParser.AS (_, s)
  | VBParser.ID (s, _) -> s
  | VBParser.INT (n, _) -> string_of_int n
  | VBParser.NEWLINE _ -> "Newline"
  | VBParser.EOF -> "EOF"
