image: docker:latest

stages:
  - build-ocaml
  - build-angular
  - test-angular

build-ocaml:
  image: ocaml/opam2:alpine-3.9-ocaml-4.07
  stage: build-ocaml
  artifacts:
    paths:
      - src/compiler/_build/
  script:
    - sudo apk update
    - sudo apk add m4
    - opam update
    - ocamlc --version
    - opam --version
    - opam install -y dune menhir js_of_ocaml-compiler js_of_ocaml-ppx js_of_ocaml ounit
    - cd src/compiler
    - dune runtest
    - dune build ./JerooCompiler.bc.js --profile release

build-angular:
  image: node:8.15-alpine
  stage: build-angular
  artifacts:
    paths:
      - dist/
  script:
    - yarn --version
    - yarn install
    - yarn lint
    - yarn build --prod

test-angular:
  image: timbru31/node-chrome:slim
  stage: test-angular
  script:
    - apt-get update && apt-get install -y procps
    - google-chrome-stable --version
    - yarn --version
    - yarn install
    - yarn test --no-watch --no-progress --browsers=ChromeHeadlessCI
    - yarn e2e --protractor-config=e2e/protractor-ci.conf.js
