image: docker:latest

stages:
  - build-ocaml
  - build-angular
  - test-angular
  - generate-documentation

build-ocaml:
  image: ocaml/opam2:alpine-3.9-ocaml-4.07
  stage: build-ocaml
  artifacts:
    paths:
      - src/compiler/_build/
  script:
    - cd src/compiler
    - sudo apk update
    - sudo apk add m4
    - opam update && opam upgrade
    - ocamlc --version
    - opam --version
    - opam install --deps-only .
    - eval $(opam env)
    - dune build ./JerooCompiler.bc.js --profile release
    - dune runtest

build-angular:
  image: node:8.15-alpine
  stage: build-angular
  artifacts:
    paths:
      - dist/
  script:
    - yarn --version
    - yarn install
    - yarn lint
# remove the --base-href when the sites moves into the "/" directory
    - yarn build --base-href=/beta/ --prod

test-angular:
  image: timbru31/node-chrome:slim
  stage: test-angular
  script:
    - apt-get update && apt-get install -y procps
    - google-chrome-stable --version
    - yarn --version
    - yarn install
    - yarn test --no-watch --no-progress --browsers=ChromeHeadlessCI
    - yarn e2e --protractor-config=e2e/protractor-ci.conf.js

generate-typescript-documentation:
  image: node:8.15-alpine
  stage: generate-documentation
  only:
    - master
  artifacts:
    paths:
      - docs
  script:
    - yarn --version
    - yarn install
    - yarn doc --out docs src/

generate-ocaml-documentation:
  image: ocaml/opam2:alpine-3.9-ocaml-4.07
  stage: generate-documentation
  only:
    - master
  artifacts:
    paths:
      - src/compiler/_build/default/_doc/_html
  script:
    - sudo apk update
    - sudo apk add m4
    - opam update
    - ocamlc --version
    - opam --version
    - opam install dune odoc menhir
    - odoc --version
    - cd src/compiler
    - dune build lib @doc-private
