image: ubuntu:18.04
before_script:
  - apt-get update -qq && apt-get -y -qq upgrade
  - apt-get install -y make gcc m4
  - apt install -y -qq software-properties-common
  - add-apt-repository ppa:avsm/ppa
  - apt-get -y update
  - apt-get install opam -y
  - opam --version
  - opam init --bare
  - eval `opam env`
  - opam switch create 4.07.1
  - eval `opam env`
  - ocaml --version
  - opam install -y dune menhir js_of_ocaml-compiler js_of_ocaml-ppx js_of_ocaml ounit
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install nodejs -y
  - node -v
  - npm -v
  - npm install -g yarn

build:
  script:
    - cd src/compiler
    - dune build ./jeroo_compiler.bc.js
    - cd ../..
    - yarn install
    - yarn build

lint-typescript:
  script:
    - yarn install
    - yarn lint

test:
  script:
    - curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb --output google-chrome.deb
    - dpkg -i google-chrome.deb
    - apt-get install -f
    - cd src/compiler
    - dune build ./jeroo_compiler.bc.js
    - dune runtest
    - cd ../..
    - yarn test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    - yarn e2e -- --protractor-config=e2e/protractor-ci.conf.js
