image: ubuntu:18.04
before_script:
  - apt-get update -qq && apt-get -y -qq upgrade
  - apt-get install -y make gcc m4
  - apt install -y -qq software-properties-common
  - add-apt-repository ppa:avsm/ppa
  - apt-get -y update
  - apt-get install opam -y
  - opam --version
  - opam init --bare
  - eval `opam env`
  - opam switch create 4.07.1
  - eval `opam env`
  - ocaml --version
  - opam install -y dune menhir js_of_ocaml-compiler js_of_ocaml-ppx js_of_ocaml
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install nodejs -y
  - node -v
  - npm -v

build-frontend:
  script:
    - cd src/compiler
    - dune build ./jaroo_compiler.bc.js
    - cd ../..
    - npm install
    - ng build --prod


