image: docker:latest

stages:
  - build-ocaml
  - build-angular
  - test-angular
  - generate-documentation

build-ocaml:
  image: ocaml/opam2:alpine-3.9-ocaml-4.07
  stage: build-ocaml
  artifacts:
    paths:
      - src/compiler/_build/
  script:
    - cd src/compiler
    - sudo apk update
    - sudo apk add m4
    - opam update && opam upgrade
    - ocamlc --version
    - opam --version
    - opam install --deps-only .
    - eval $(opam env)
    - dune build ./JerooCompiler.bc.js --profile release
    - dune runtest

build-angular:
  image: node:12-alpine
  stage: build-angular
  artifacts:
    paths:
      - dist/
  script:
    - node --version
    - yarn --version
    - yarn install
    - yarn lint
# remove the --base-href when the sites moves into the "/" directory
    - yarn build --base-href=/beta/ --prod

test-angular:
  image: ubuntu:18.04
  stage: test-angular
  script:
    - apt-get -qq update
    - apt-get -qq upgrade
    - apt-get install -qq -o=Dpkg::Use-Pty=0 gnupg2 curl firefox -y
    - firefox --version
    - apt install gnupg2 curl -yq
    - curl -sL https://deb.nodesource.com/setup_12.x | bash -
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
    - apt -qq update
    - apt install -qq -o=Dpkg::Use-Pty=0 nodejs yarn -y
    - node --version
    - yarn --version
    - yarn install
    - ./node_modules/protractor/bin/webdriver-manager update
    - yarn test --no-watch --no-progress --browsers=FirefoxHeadlessCI
    - yarn e2e --protractor-config=e2e/protractor-ci.conf.js

generate-typescript-documentation:
  image: node:12-alpine
  stage: generate-documentation
  only:
    - master
  artifacts:
    paths:
      - docs
  script:
    - node --version
    - yarn --version
    - yarn install
    - yarn doc --out docs src/

generate-ocaml-documentation:
  image: ocaml/opam2:alpine-3.9-ocaml-4.07
  stage: generate-documentation
  only:
   - master
  artifacts:
    paths:
      - src/compiler/_build/default/_doc/_html
  script:
    - sudo apk update
    - sudo apk add m4
    - opam update
    - ocamlc --version
    - opam --version
    - cd src/compiler
    - opam install --deps-only .
    - opam install odoc
    - odoc --version
    - dune build lib @doc-private
