* Jeroo Bytecode
** Loads
*** CSR n
    - Description:

      Set the current Jeroo register to /n/.
** Jumps
*** JUMP n
    - Description:

      Set the PC to /n/.
*** BZ n
    - Description:

      Peek at the top of the cmp stack, if it is a 0 set the PC to /n/.
** Jeroo Actions
*** NEW id, x, y, numFlowers, compass direction
    - Description:

      Create a Jeroo with /id/ located at /x/, /y/, holding /numFlowers/ flowers and facing direction /compass direction/.
      /Compass Direction/ can be either 0 (NORTH), EAST (1), SOUTH (2), WEST (3).
*** TURN relative direction
    - Description:

      Turn the current Jeroo /relative direction/. /Direction/ can be either 1 (left), 0 (don't turn), 3 (right)
*** HOP n
    - Description:

      Hop the current Jeroo /n/ steps. /n/ must be greater than 0.
*** TOSS
    - Description:

      Toss a flower onto a net AHEAD of the Jeroo. If a net exists,
      it will be destroyed. A flower is lost regardless of whether a net 
      exists or not. If the Jeroo has no flowers, this operation is ignored.
*** PLANT
    - Description:

      Have the current Jeroo place one flower at it's current location.
      If the Jeroo has no flower, this operation is ignored.
*** GIVE relative direction
    - Description:
 
      Give a flower to the Jeroo /relative direction/ of the current Jeroo.
      Direction can be either AHEAD (0), LEFT (3), RIGHT (1), or HERE (-1).

** Boolean Logic
*** TRUE
    - Description:
  
    Push a 1 onto the top of the cmp stack.
*** FALSE
    - Description:

      Push a 0 onto the top of the cmp stack.
*** HASFLWR
    - Description:

      If the current Jeroo has a flower, push a 1 to the cmp stack, else push a 0.
*** ISNET relative direction
    - Description:

      If the square in the /relative direction/ of the current Jeroo is a net, push a 1 to the cmp stack, else push a 0.
      /Relative Direction/ can be either AHEAD (0), LEFT (3), RIGHT (1), or HERE (-1)
*** ISWATER relative direction
    - Description:

      If the square in the /direction/ of the current Jeroo is a net, push a 1 to the cmp stack, else push a 0.
      /Relative Direction/ can be either AHEAD (0), LEFT (3), RIGHT (1), or HERE (-1)
*** ISJEROO 
    - Description:

      If the square in the /direction/ of the current Jeroo is a net, push a 1 to the cmp stack, else push a 0.
      /Direction/ can be either AHEAD (0), LEFT (3), RIGHT (1), or HERE (-1)
*** NOT
    - Description:

      Peek at the top of the cmp stack and invert it. If the top of the cmp stack is a 1, push a 0, else push a 1.
*** AND
    - Description:

      Pop the top two elements off the comparison stack and perform a logical and on the two elements and 
      push the result onto the top of the cmp stack.
*** OR
    - Description:

     Pop the top two elements off the comparison stack and perform a logical or on the two elements and
     push the result onto the top of the cmp stack.
** Functions
*** RETR
    - Description:
      
      Peek at the top value of the call stack and set the PC to that value.
*** CALLBK
    - Description:

      Push a new value onto the call stack that is one after where we currently are. 
